# NOTE this shoudl be ran INSIDE the vcluster

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: "ytl@slac.stanford.edu"
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: "ppascual@slac.stanford.edu"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admins
subjects:
- kind: User
  name: "jgarra@slac.stanford.edu"
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: "cmayes@slac.stanford.edu"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
