# Enable HA mode
enableHA: true

# not supported with k8s yet
#securityContext:
#  runAsUser: 15693 # cryo-daq
#  fsGroup: 3591 # cryo-data
#  runAsGroup: 3591
#  runAsNonRoot: true

vcluster:
  extraArgs:
  - --oidc-issuer-url=https://dex.slac.stanford.edu
  - --oidc-client-id=vcluster--k8s-sandbox
  - --oidc-username-claim=name
  - --oidc-groups-claim=groups

storage:
  persistence: true
  size: 1Gi
  className: wekafs--sdf-k8s01

# Scale up syncer replicas
syncer:
  replicas: 1

# Scale up etcd
etcd:
  image: k8s.gcr.io/etcd:3.5.1-0
  replicas: 1
  storage:
    persistence: true
    className: wekafs--sdf-k8s01

# Scale up controller manager
controller:
  replicas: 1

# Scale up api server
api:
  image: k8s.gcr.io/kube-apiserver:v1.23.2
  replicas: 1
  extraArgs: 
  - --oidc-issuer-url=https://dex.slac.stanford.edu
  - --oidc-client-id=vcluster--k8s-sandbox
  - --oidc-username-claim=email
  - --oidc-groups-claim=groups

controller:
  image: k8s.gcr.io/kube-controller-manager:v1.23.2

sync:
  nodes:
    enabled: false
    #nodeSelector: edu.stanford.slac.sdf.project=rubin


