apiVersion: v1
data:
  config: |
    address-pools:
    - name: internal
      protocol: layer2
      addresses:
      - 172.23.99.146-172.23.99.180
      speakers:
      - neb0002.slac.stanford.edu
      - neb0007.slac.stanford.edu
kind: ConfigMap
metadata:
  annotations:
  name: config
  namespace: metallb-system
