apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: metallb
    component: speaker
  name: speaker
  namespace: metallb-system
spec:
  template:
    spec:
       containers:
       - name: speaker
         imagePullPolicy: Always

