# Enable HA mode
enableHA: true

storage:
  persistence: true
  size: 1Gi
  className: wekafs--sdf-k8s01

# Scale up syncer replicas
syncer:
  replicas: 1

# Scale up etcd
etcd:
  replicas: 1
  storage:
    persistence: true
    className: wekafs--sdf-k8s01

# Scale up controller manager
controller:
  replicas: 1

# Scale up api server
api:
  replicas: 1
  extraArgs: 
  - --oidc-issuer-url=https://dex.slac.stanford.edu 
  - --oidc-client-id=vcluster--supercdms
  - --oidc-username-claim=email
  - --oidc-groups-claim=groups
