apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
- ns.yaml
- sdf-home-helm.yaml
- sdf-group-supercdms-helm.yaml
- sdf-group-ard-helm.yaml
- sdf-group-rubin-helm.yaml
- sdf-group-rubin-datasets-helm.yaml
- sdf-group-rubin-scratch-helm.yaml
- sdf-group-lsst-helm.yaml
- sdf-group-cryoem-dev-helm.yaml
- sdf-group-cryoem-helm.yaml
- sdf-group-cryoem-exp-helm.yaml

# we need to use our own custom image due to changes in the handling of how we deal with lustre etc.
images:
- name: rancher/local-path-provisioner
  newName: slaclab/local-path-provisioner
  newTag: latest
