apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
- ns.yaml
- sdf-group-supercdms-helm.yaml
- sdf-group-ard-helm.yaml
- sdf-group-rubin-helm.yaml

images:
- name: rancher/local-path-provisioner
  newName: slaclab/local-path-provisioner
  newTag: latest
