---
# Source: local-path-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdf-group-supercdms-local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
---
# Source: local-path-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sdf-group-supercdms
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |-
    {
      "nodePathMap": 
        [
          {
            "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths": [
              "/sdf/group/supercdms/pvtest/"
            ]
          }
        ]
    }
  setup: |-
    
    #!/bin/sh
    set -eu
    echo "nothing to do"
  teardown: |-
    
    #!/bin/sh
    set -eu
    echo "nothing to do"
  helperPod.yaml: |-
    
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
---
# Source: local-path-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sdf-group-supercdms
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
provisioner: local-path-provisioner.local/sdf-group-supercdms
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
---
# Source: local-path-provisioner/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdf-group-supercdms-local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "persistentvolumes", "pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
# Source: local-path-provisioner/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdf-group-supercdms-local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sdf-group-supercdms-local-path-provisioner
subjects:
  - kind: ServiceAccount
    name: sdf-group-supercdms-local-path-provisioner
    namespace: local-path-storage
---
# Source: local-path-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdf-group-supercdms-local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.22-dev
    app.kubernetes.io/instance: sdf-group-supercdms
    app.kubernetes.io/version: "v0.0.22-dev"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local-path-provisioner
      app.kubernetes.io/instance: sdf-group-supercdms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-path-provisioner
        app.kubernetes.io/instance: sdf-group-supercdms
    spec:
      serviceAccountName: sdf-group-supercdms-local-path-provisioner
      containers:
        - name: local-path-provisioner
          image: "rancher/local-path-provisioner:master-head"
          imagePullPolicy: Always
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --service-account-name
            - sdf-group-supercdms-local-path-provisioner
            - --provisioner-name
            - local-path-provisioner.local/sdf-group-supercdms
            - --helper-image
            - "busybox:latest"
            - --configmap-name
            - sdf-group-supercdms
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              value: local-path-storage
          resources:
            {}
      volumes:
        - name: config-volume
          configMap:
            name: sdf-group-supercdms
