apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault--prod
spec:
  replicas: 3 
  template:
    spec:
      containers:
      - name: vault
        env:
        - name: HTTP_PROXY
          value: http://squid.slac.stanford.edu:3128
        - name: HTTPS_PROXY
          value: http://squid.slac.stanford.edu:3128
        - name: NO_PROXY
          value: .vault-internal,localhost,.localdomain,squid.slac.stanford.edu,.slac.stanford.edu
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "vault" 
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
