apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: postgres
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
spec:
  type: LoadBalancer
  selector:
    postgres-operator.crunchydata.com/cluster: hippo-ha
    postgres-operator.crunchydata.com/role: pgbouncer
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: pgbouncer
