namespace: postgres

resources:
- namespace.yaml
- huge-pages-fix.yaml
- zalando-postgres.yaml
- telegraf.yaml

configMapGenerator:
- name: telegraf-postgres
  files:
  - telegraf.conf
  - postgresql_custom_data.conf 
