apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: telegraf-postgres
spec:
  selector:
    matchLabels:
      name: telegraf-postgres
  template:
    metadata:
      labels:
        name: telegraf-postgres
    spec:
      containers:
      - name: telegraf-postgres
        image: slaclab/telegraf-execd-pg-custom:1.22.1
        env:
        - name: HOSTNAME
          value: usdf-butler
#        - name: HOST_PROC
#          value: /rootfs/proc
#        - name: HOST_SYS
#          value: /rootfs/sys
        - name: MONITOR_HOST
          value: https://influxdb.slac.stanford.edu:443
        - name: MONITOR_DATABASE
          value: rubin
        - name: MONITOR_CADENCE
          value: 1m
        - name: POSTGRES_HOST
          value: usdf-butler
        - name: POSTGRES_DB
          value: butler
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: monitoring.usdf-butler.credentials.postgresql.acid.zalan.do
              key: username
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monitoring.usdf-butler.credentials.postgresql.acid.zalan.do
              key: password
              optional: false
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
#        - mountPath: /rootfs/sys
#          name: sys
#          readOnly: true
#        - mountPath: /rootfs/proc
#          name: proc
#          readOnly: true
#        - mountPath: /var/run/docker.sock
#          name: docker-socket
#          readOnly: true
#        - mountPath: /var/run/utmp
#          name: utmp
#          readOnly: true
        - mountPath: /etc/telegraf/telegraf.conf
          name: config
          subPath: telegraf.conf
        - mountPath: /opt/pg_custom/postgresql_custom_data.conf
          name: config
          subPath: postgresql_custom_data.conf
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
#      - hostPath:
#          path: /sys
#          type: ""
#        name: sys
#      - hostPath:
#          path: /var/run/docker.sock
#          type: ""
#        name: docker-socket
#      - hostPath:
#          path: /proc
#          type: ""
#        name: proc
#      - hostPath:
#          path: /var/run/utmp
#          type: ""
#        name: utmp
      - configMap:
          defaultMode: 420
          name: telegraf-postgres
        name: config
