
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: usdf-butler
  namespace: postgres
spec:
  teamId: "usdf"
  #labels:
  #  application: butler
  #  environment: prod
  resources:
    requests:
      cpu: '16'
      memory: 64Gi
    limits:
      cpu: '32'
      memory: 128Gi
  volume:
    size: 1000Gi
  numberOfInstances: 2
  users:
    rubin:  # database owner
    #- superuser
    - createdb
    #butler:
    #- createdb
    monitoring: []
  databases:
    butler: rubin  # dbname: owner
  #preparedDatabases:
  #  bar: {}
  postgresql:
    version: "14"
  # required to avoid huge pages issues
  additionalVolumes:
  - name: pg-init-config-9
    mountPath: /usr/share/postgresql/9.6/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  - name: pg-init-config-10
    mountPath: /usr/share/postgresql/10/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  - name: pg-init-config-11
    mountPath: /usr/share/postgresql/11/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  - name: pg-init-config-12
    mountPath: /usr/share/postgresql/12/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  - name: pg-init-config-13
    mountPath: /usr/share/postgresql/13/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  - name: pg-init-config-14
    mountPath: /usr/share/postgresql/14/postgresql.conf.sample
    subPath: postgresql.conf.sample
    volumeSource:
      configMap:
        name: pg-init-config
  connectionPooler:
    numberOfInstances: 2
    mode: session
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi

    
