apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex 
      initContainers:
      - image: vault:1.7.0
        name: vault-agent-init
        command:
        - vault
        - agent 
        - -config=/vault/config/config.hcl
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
        - name: vault-agent
          mountPath: /vault/agent
        - name: vault-config
          mountPath: /vault/config
        - name: dex-template
          mountPath: /vault/templates/
      containers:
      - image: quay.io/dexidp/dex:v2.19.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: https
          containerPort: 32000
          protocol: TCP
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-secrets
          mountPath: /etc/dex/cfg/
        - name: certs
          mountPath: /etc/dex/tls
          readOnly: true
      volumes:
      - name: vault-config
        configMap:
          name: vault
      - name: vault-agent
        emptyDir: {}
      - name: vault-secrets
        emptyDir: {}
      - name: dex-template
        configMap: 
          name: dex
      - name: certs
        secret:
          secretName: dex-certs
          items:
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
          - key: adfs.slac.stanford.edu.cer
            path: adfs.slac.stanford.edu.cer
