---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth-system
  annotations:
    metallb.universe.tf/address-pool: internal
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - name: dex
    port: 32000
    protocol: TCP
    targetPort: 32000
    #nodePort: 32000
  selector:
    app: dex


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex
  namespace: auth-system
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - secretName: dex
    hosts:
    - dex.slac.stanford.edu
  rules:
  - host: dex.slac.stanford.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: dex
          servicePort: 32000
