---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth-system
  annotations: []
  #  metallb.universe.tf/address-pool: internal
spec:
  type: ClusterIP
  #type: LoadBalancer
  ports:
  - name: http
    port: 32000
    protocol: TCP
  - name: telemetry
    port: 5558
    protocol: TCP
  selector:
    app: dex


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  namespace: auth-system
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: dex.slac.stanford.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: dex
            port:
              name: http
