apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: raft.vault--prod
spec:
  groups:
  - system:authenticated
  request: ${REQUEST}
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - client auth
