apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/service: https://vault.slac.stanford.edu
        # vault.hashicorp.com/tls-server-name: vault.slac.stanford.edu # seems to fault with tls
        ## this, unfortuantely, needs to match the cluster name, eitehr k8s-api01 or k8s-master, to match where we're runnign this
        # vault.hashicorp.com/auth-path: auth/k8s-master
        vault.hashicorp.com/auth-path: auth/k8s-api01
        vault.hashicorp.com/role: dex
        #vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/secret-volume-path-config.yaml: /etc/dex/cfg/
        vault.hashicorp.com/agent-inject-secret-config.yaml: secret/dexidp/connectors/ldap-ad
        vault.hashicorp.com/agent-inject-template-config.yaml: |
          issuer: https://dex.slac.stanford.edu
          storage:
            type: kubernetes
            config:
              inCluster: true
          web:
            https: 0.0.0.0:32000
            tlsCert: /etc/dex/tls/tls.crt
            tlsKey: /etc/dex/tls/tls.key
          telemetry:
            http: 0.0.0.0:5558
          connectors:
          - type: ldap
            id: unix
            name: Unix LDAP
            config:
              host: ldap-unix.slac.stanford.edu:636
              insecureSkipVerify: true
              userSearch:
                baseDN: ou=Accounts,dc=slac,dc=stanford,dc=edu
                filter: ''
                username: uid
                idAttr: uid
                emailAttr: mail
                nameAttr: gecos
              groupSearch:
                baseDN: ou=Group,dc=slac,dc=stanford,dc=edu
                filter: "(objectclass=posixGroup)"
                userAttr: uid
                groupAttr: memberUid
                nameAttr: cn
          - type: ldap
            id: ad
            name: Windows LDAP
            config:
              host: ldap-ad.slac.stanford.edu:636
              {{- with secret "secret/dexidp/connectors/ldap-ad" }}
              bindDN: {{ .Data.data.bindDN }}
              bindPW: {{ .Data.data.bindPW }}
              {{- end }}
              userSearch:
                baseDN: DC=win,DC=slac,DC=Stanford,DC=edu
                filter: "(objectClass=person)(objectcategory=user)"
                username: sAMAccountName
                idAttr: userPrincipalName
                emailAttr: mail
                nameAttr: name
              groupSearch:
                baseDN: DC=win,DC=slac,DC=Stanford,DC=edu
                filter: "(objectClass=group)"
                userMatchers:
                - userAttr: DN
                  groupAttr: member
                nameAttr: cn
          - type: saml
            id: saml
            name: SLAC SSO
            config:
              ssoURL: https://adfs.slac.stanford.edu/adfs/ls  
              ca: /etc/dex/tls/adfs.slac.stanford.edu.cer
              redirectURI: https://dex.slac.stanford.edu/callback
              usernameAttr: urn:oid:1.3.6.1.4.1.5923.1.1.1.6
              emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
              entityIssuer: https://dex.slac.stanford.edu/callback
              #groupsAttr: groups
              oauth2:
                skipApprovalScreen: true
          staticClients:
          - name: k8s-login
            id: k8s-login
            redirectURIs:
            - 'https://k8s-login.slac.stanford.edu/callback'
            secret: {{ with secret "secret/dexidp/staticClients/k8s-login" }}{{ .Data.data.secret }}{{ end }}
          - name: k8s-master-login
            id: k8s-master-login
            redirectURIs:
            - 'https://k8s-master-login.slac.stanford.edu/callback'
            secret: {{ with secret "secret/dexidp/staticClients/k8s-master-login" }}{{ .Data.data.secret }}{{ end }}
          - name: vault
            id: vault
            redirectURIs:
            - 'https://vault.slac.stanford.edu/ui/vault/auth/oidc/oidc/callback'
            secret: {{ with secret "secret/dexidp/staticClients/vault" }}{{ .Data.data.secret }}{{ end }}
          - name: rubin-data-dev
            id: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.id }}{{ end }}
            redirectURIs:
            - 'https://rubin-data-dev.slac.stanford.edu/argo-cd/callback'
            secret: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.secret }}{{ end }}
          

    spec:
      serviceAccountName: dex 
      containers:
      - image: quay.io/dexidp/dex:v2.19.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: https
          containerPort: 32000
          protocol: TCP
        volumeMounts:
        #- name: config
        #  mountPath: /etc/dex/cfg
        - name: certs
          mountPath: /etc/dex/tls
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: dex-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: certs
        secret:
          secretName: dex-certs
          items:
          - key: tls.key
            path: tls.key
          - key: tls.crt
            path: tls.crt
          - key: adfs.slac.stanford.edu.cer
            path: adfs.slac.stanford.edu.cer
