apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/dexidp/helloworld"
        vault.hashicorp.com/role: "dex"

