---
apiVersion: v1
kind: Service
metadata:
  name: vouch
  namespace: auth-system
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    protocol: TCP
  selector:
    app: vouch

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vouch
  namespace: auth-system
  annotations:
spec:
  rules:
  - host: vouch-dev.slac.stanford.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: vouch
          servicePort: http

