---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: gangway-sdf-k8s01
spec:
  rules:
  - host: k8s.slac.stanford.edu
    http:
      paths:
      - backend:
          service:
            name: gangway-sdf-k8s01
            port:
              name: "http"
        path: /sdf-k8s01
        pathType: Prefix

---

kind: Service
apiVersion: v1
metadata:
  name: gangway-sdf-k8s01
  namespace: auth-system
  labels:
    app: gangway
    cluster: sdf-k8s01
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: "http"
  selector:
    app: gangway
    cluster: sdf-k8s01

---

