apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-prod

resources:
- ns.yaml
#- cm.yaml
- pv.yaml
- sts.yaml
- endpoints.yaml

configMapGenerator:
- name: grafana
  files:
  - grafana.ini

secretGenerator:
- name: grafana
  files:
  - etc/admin-user
  - etc/admin-password
  literals:
  - ldap-toml=""

images:
- name: grafana/grafana
  # newTag: 6.6.0 
  newTag: 7.1.3
