apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- ns.yaml
- sts.yaml
- endpoints.yaml
- renderer.yaml

configMapGenerator:
- name: grafana
  files:
  - etc/grafana.ini

secretGenerator:
- name: grafana
  files:
  - etc/.secrets/admin-user
  - etc/.secrets/admin-password
  - etc/.secrets/oidc-id
  - etc/.secrets/oidc-secret
  literals:
  - ldap-toml=""

images:
- name: grafana/grafana
  #newTag: 7.1.3
  newTag: 8.4.5
