apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    metallb.universe.tf/address-pool: farm04-openstack
    metallb.universe.tf/allow-shared-ip: lsstcam-postgres--prod
spec:
  loadBalancerIP: 172.23.99.149
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  annotations:
    metallb.universe.tf/address-pool: farm04-openstack
    metallb.universe.tf/allow-shared-ip: lsstcam-postgres--prod
spec:
  loadBalancerIP: 172.23.99.149
