apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana--dev

resources:
- ns.yaml
#- cm.yaml
- pv.yaml
- sts.yaml
- endpoints.yaml

configMapGenerator:
- name: grafana
  files:
  - grafana.ini

secretGenerator:
- name: grafana
  files:
  - etc/admin-user
  - etc/admin-password
  - etc/oidc-id
  - etc/oidc-secret
  literals:
  - ldap-toml=""

images:
- name: grafana/grafana
  newTag: 8.0.3
