---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: gangway-k8s-master
spec:
  rules:
  - host: k8s.slac.stanford.edu
    http:
      paths:
      - backend:
          service:
            name: gangway-k8s-master
            port:
              name: "http"
        path: /k8s-master
        pathType: Prefix

---

kind: Service
apiVersion: v1
metadata:
  name: gangway-k8s-master
  namespace: auth-system
  labels:
    app: gangway-k8s-master
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: "http"
  selector:
    app: gangway
    cluster: k8s-master

---

