apiVersion: apps/v1
kind: Deployment
metadata:
  name: gangway-k8s-master
  labels:
    app: gangway
    cluster: k8s-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
      cluster: k8s-master
  strategy:
  template:
    metadata:
      labels:
        app: gangway
        cluster: k8s-master
        revision: "1"
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v3.2.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway
                  key: session-key
            - name: GANGWAY_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: templates
              mountPath: /gangway/templates/
          livenessProbe:
            httpGet:
              path: /k8s-master
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /k8s-master
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: templates
          configMap:
            name: templates
        - name: gangway
          secret:
            secretName: gangway
            items:
            - key: gangway.yaml
              path: gangway.yaml
---
