issuer: https://dex.slac.stanford.edu
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:32000
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key
telemetry:
  http: 0.0.0.0:5558
connectors:
- type: oidc
  id: cilogon
  name: CILogon
  config:
    issuer: https://cilogon.org
    clientID: {{ with secret "secret/dexidp/connectors/cilogon" }}{{ index .Data.data "client-id" }}{{ end }} 
    clientSecret: {{ with secret "secret/dexidp/connectors/cilogon" }}{{ index .Data.data "client-secret" }}{{ end }}
    redirectURI: https://dex.slac.stanford.edu/callback
    insecureSkipEmailVerified: true
    scopes:
    - org.cilogon.userinfo
    - profile
    #emailAttr: eppn
    # no email, as we need to overload it from the org.cilogon.userinfo scope
    claimMapping:
      email: eppn
- type: saml
  id: saml
  name: SLAC SSO
  config:
    ssoURL: https://adfs.slac.stanford.edu/adfs/ls
    ca: /etc/dex/tls/adfs.slac.stanford.edu.cert
    redirectURI: https://dex.slac.stanford.edu/callback
    #usernameAttr: urn:oid:1.3.6.1.4.1.5923.1.1.1.6
    usernameAttr: http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
    emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
    entityIssuer: https://dex.slac.stanford.edu/callback
    #groupsAttr: groups
    oauth2:
      skipApprovalScreen: true
    claimMapping:
      preferred_username: http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
staticClients:
- name: k8s-login
  id: k8s-login
  redirectURIs:
  - 'https://k8s.slac.stanford.edu/k8s-login/callback'
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/dexidp/staticClients/k8s-login" }}{{ .Data.data.secret }}{{ end }}
- name: k8s-master
  id: k8s-master
  redirectURIs:
  - 'https://k8s.slac.stanford.edu/k8s-master/callback'
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/dexidp/staticClients/k8s-master-login" }}{{ .Data.data.secret }}{{ end }}
- name: sdf-k8s01
  id: sdf-k8s01
  redirectURIs:
  - 'https://k8s.slac.stanford.edu/sdf-k8s01/callback'
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/dexidp/staticClients/sdf-k8s01" }}{{ .Data.data.secret }}{{ end }}
- name: vault
  id: vault
  redirectURIs:
  - 'http://localhost:8250/oidc/callback'
  - 'https://vault.slac.stanford.edu/ui/vault/auth/oidc/oidc/callback'
  secret: {{ with secret "secret/dexidp/staticClients/vault" }}{{ .Data.data.secret }}{{ end }}
- name: rubin-data-dev
  id: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.id }}{{ end }}
  redirectURIs:
  - 'https://rubin-data-dev.slac.stanford.edu/argo-cd/callback'
  secret: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.secret }}{{ end }}
- name: grafana-dev
  id: {{ with secret "secret/dexidp/staticClients/grafana-prod" }}{{ .Data.data.id }}{{ end }}
  redirectURIs:
  - 'https://grafana.slac.stanford.edu/login/generic_oauth'
  secret: {{ with secret "secret/dexidp/staticClients/grafana-prod" }}{{ .Data.data.secret }}{{ end }}
- name: grafana-dev
  id: {{ with secret "secret/dexidp/staticClients/grafana-dev" }}{{ .Data.data.id }}{{ end }}
  redirectURIs:
  - 'https://grafana-dev.slac.stanford.edu/login/generic_oauth'
  secret: {{ with secret "secret/dexidp/staticClients/grafana-dev" }}{{ .Data.data.secret }}{{ end }}
- name: vouch
  id: vouch
  redirectURIs:
  - https://vouch.slac.stanford.edu/auth
  secret: {{ with secret "secret/dexidp/staticClients/vouch" }}{{ .Data.data.secret }}{{ end }}
- name: vouch-dev
  id: vouch-dev
  redirectURIs:
  - https://vouch-dev.slac.stanford.edu/auth
  secret: {{ with secret "secret/dexidp/staticClients/vouch-dev" }}{{ .Data.data.secret }}{{ end }}
- name: gafaelfawr
  id: {{ with secret "secret/dexidp/staticClients/gafaelfawr" }}{{ index .Data.data "oidc-client-id" }}{{ end }}
  redirectURIs:
  - https://gafaelfawr.slac.stanford.edu/auth
  secret: {{ with secret "secret/dexidp/staticClients/gafaelfawr" }}{{ index .Data.data "oidc-client-secret" }}{{ end }}
- name: rubin-usdf-staffrsp-dev
  id: {{ with secret "secret/rubin/usdf-staffrsp-dev/gafaelfawr" }}{{ index .Data.data "oidc-client-id" }}{{ end }}
  redirectURIs:
  - https://rubin-data-dev.slac.stanford.edu/login
  secret: {{ with secret "secret/rubin/usdf-staffrsp-dev/gafaelfawr" }}{{ index .Data.data "oidc-client-secret" }}{{ end }}
- name: vcluster--ard
  id: vcluster--ard
  redirectURIs:
  - https://k8s.slac.stanford.edu/ard/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/ard/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--cryoem
  id: vcluster--cryoem
  redirectURIs:
  - https://k8s.slac.stanford.edu/cryoem/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/cryoem/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--cryoem--dev
  id: vcluster--cryoem--dev
  redirectURIs:
  - https://k8s.slac.stanford.edu/cryoem--dev/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/cryoem/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--supercdms
  id: vcluster--supercdms
  redirectURIs:
  - https://k8s.slac.stanford.edu/supercdms/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/supercdms/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--lcls-data-ana
  id: vcluster--lcls-data-ana
  redirectURIs:
  - https://k8s.slac.stanford.edu/lcls-data-ana/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/lcls/lcls-data-ana/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--usdf-staffrsp--dev
  id: vcluster--usdf-staffrsp--dev
  redirectURIs:
  - https://k8s.slac.stanford.edu/usdf-staffrsp--dev/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/rubin/usdf-staffrsp-dev/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--usdf-butler
  id: vcluster--usdf-butler
  redirectURIs:
  - https://k8s.slac.stanford.edu/usdf-butler/callback
  - http://localhost:8000
  - http://localhost:18000
  secret: {{ with secret "secret/rubin/usdf-butler/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
