apiVersion: v1
kind: Service
metadata:
  name: weka-k8s01-export
  annotations:
    prometheus.io/port: "8001"
    prometheus.io/scrape: "true"
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: weka-k8s01

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8101"
    prometheus.io/scrape: "true"
  name: weka-k8s01-quota
spec:
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
  selector:
    app: weka-k8s01

