apiVersion: apps/v1
kind: Deployment
metadata:
  name: weka-k8s01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weka-k8s01
  template:
    metadata:
      labels:
        app: weka-k8s01
    spec:
      containers:
      - name: export
        image: wekasolutions/export:latest
        command:
        - /weka/export
        - -v
        - -c
        - /config/export.yml
        ports:
        - name: metrics
          containerPort: 8001
        volumeMounts:
        - mountPath: "/config/export.yml"
          name: config
          readOnly: true
          subPath: "export.yml"
        - mountPath: "/weka/.weka"
          name: auth
          readOnly: true
      - name: quota
        image: wekasolutions/quota-export:latest
        command:
        - /weka/quota-export
        - -v
        - -c
        - /config/quota-export.yml
        ports:
        - name: quota
          containerPort: 8101
        volumeMounts:
        - mountPath: "/config/quota-export.yml"
          name: config
          readOnly: true
          subPath: "quota-export.yml"
        - mountPath: "/weka/.weka"
          name: auth
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: weka-k8s01
      - name: auth
        secret:
          secretName: weka-k8s01

---

apiVersion: v1
kind: Service
metadata:
  name: weka-k8s01-export
  annotations:
    prometheus.io/port: "8001"
    prometheus.io/scrape: "true"
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: weka-k8s01

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8101"
    prometheus.io/scrape: "true"
  name: weka-k8s01-quota
spec:
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
  selector:
    app: weka-k8s01

---
