apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- deployment.yaml
- endpoints.yaml

configMapGenerator:
- name: weka-k8s01
  files:
  - etc/export.yml
  - etc/quota-export.yml

secretGenerator:
- name: weka-k8s01
  files:
  - auth-token.json=etc/.auth-token.json

#images:
#- name: grafana/grafana
#  #newTag: 7.1.3
#  newTag: 8.4.3
