apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- k8s01.yaml
- sdfhome.yaml

configMapGenerator:
- name: weka-k8s01
  files:
  - etc/k8s01/export.yml
  - etc/k8s01/quota-export.yml
- name: weka-sdfhome
  files:
  - etc/sdfhome/export.yml
  - etc/sdfhome/quota-export.yml

secretGenerator:
- name: weka-k8s01
  files:
  - auth-token.json=etc/.secrets/auth-token.json.k8s01
- name: weka-sdfhome
  files:
  - auth-token.json=etc/.secrets/auth-token.json.sdfhome

#images:
#- name: grafana/grafana
#  #newTag: 7.1.3
#  newTag: 8.4.3
