issuer: https://dex-dev.slac.stanford.edu
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:32000
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key
telemetry:
  http: 0.0.0.0:5558
connectors:
#- type: ldap
#  id: unix
#  name: Unix LDAP
#  config:
#    host: ldap-unix.slac.stanford.edu:636
#    insecureSkipVerify: true
#    userSearch:
#      baseDN: ou=Accounts,dc=slac,dc=stanford,dc=edu
#      filter: ''
#      username: uid
#      idAttr: uid
#      emailAttr: mail
#      nameAttr: gecos
#    groupSearch:
#      baseDN: ou=Group,dc=slac,dc=stanford,dc=edu
#      filter: "(objectclass=posixGroup)"
#      userAttr: uid
#      groupAttr: memberUid
#      nameAttr: cn
#- type: ldap
#  id: ad
#  name: Windows LDAP
#  config:
#    host: ldap-ad.slac.stanford.edu:636
#    {{- with secret "secret/dexidp/connectors/ldap-ad" }}
#    bindDN: {{ .Data.data.bindDN }}
#    bindPW: {{ .Data.data.bindPW }}
#    {{- end }}
#    userSearch:
#      baseDN: DC=win,DC=slac,DC=Stanford,DC=edu
#      filter: "(objectClass=person)(objectcategory=user)"
#      username: sAMAccountName
#      idAttr: userPrincipalName
#      emailAttr: mail
#      nameAttr: name
#    groupSearch:
#      baseDN: DC=win,DC=slac,DC=Stanford,DC=edu
#      filter: "(objectClass=group)"
#      userMatchers:
#      - userAttr: DN
#        groupAttr: member
#      nameAttr: cn
- type: saml
  id: saml
  name: SLAC SSO
  config:
    ssoURL: https://adfs.slac.stanford.edu/adfs/ls
    ca: /etc/dex/tls/adfs.slac.stanford.edu.cert
    redirectURI: https://dex-dev.slac.stanford.edu/callback
    #usernameAttr: urn:oid:1.3.6.1.4.1.5923.1.1.1.6 #eppn
    usernameAttr: http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname
    #usernameAttr: name
    emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
    entityIssuer: https://dex-dev.slac.stanford.edu/callback
    # groupsAttr: groups
    nameIDPolicyFormat: persistent
    oauth2:
      skipApprovalScreen: true
staticClients:
- name: k8s-login
  id: k8s-login
  redirectURIs:
  - https://k8s-login.slac.stanford.edu/callback
  secret: {{ with secret "secret/dexidp/staticClients/k8s-login" }}{{ .Data.data.secret }}{{ end }}
- name: k8s-master-login
  id: k8s-master-login
  redirectURIs:
  - https://k8s-master-login.slac.stanford.edu/callback
  secret: {{ with secret "secret/dexidp/staticClients/k8s-master-login" }}{{ .Data.data.secret }}{{ end }}
- name: vault
  id: vault
  redirectURIs:
  - https://vault.slac.stanford.edu/ui/vault/auth/oidc/oidc/callback
  secret: {{ with secret "secret/dexidp/staticClients/vault" }}{{ .Data.data.secret }}{{ end }}
#- name: rubin-data-dev
#  id: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.id }}{{ end }}
#  redirectURIs:
#  - 'https://rubin-data-dev.slac.stanford.edu/argo-cd/callback'
#  secret: {{ with secret "secret/dexidp/staticClients/rubin-data-dev" }}{{ .Data.data.secret }}{{ end }}
- name: grafana-dev
  id: {{ with secret "secret/dexidp/staticClients/grafana-dev" }}{{ .Data.data.id }}{{ end }}
  redirectURIs:
  - https://grafana-dev.slac.stanford.edu/login/generic_oauth
  secret: {{ with secret "secret/dexidp/staticClients/grafana-dev" }}{{ .Data.data.secret }}{{ end }}
- name: vouch-dev
  id: vouch-dev
  redirectURIs:
  - https://vouch-dev.slac.stanford.edu/auth
  #- "https://echo-server.slac.stanford.edu"
  secret: {{ with secret "secret/dexidp/staticClients/vouch-dev" }}{{ .Data.data.secret }}{{ end }}
- name: rubin-usdf-staffrsp-dev
  id: {{ with secret "secret/rubin/usdf-staffrsp-dev/gafaelfawr" }}{{ index .Data.data "oidc-client-id" }}{{ end }}
  redirectURIs:
  - https://rubin-data-dev.slac.stanford.edu/login
  secret: {{ with secret "secret/rubin/usdf-staffrsp-dev/gafaelfawr" }}{{ index .Data.data "oidc-client-secret" }}{{ end }}
- name: vcluster--ard
  id: vcluster--ard
  redirectURIs:
  - https://k8s.slac.stanford.edu/ard/callback
  secret: {{ with secret "secret/ard/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}
- name: vcluster--supercdms
  id: vcluster--supercdms
  redirectURIs:
  - https://k8s.slac.stanford.edu/supercdms/callback
  secret: {{ with secret "secret/supercdms/kubernetes" }}{{ index .Data.data "client-secret" }}{{ end }}

