apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault--prod
  labels:
    helm.sh/chart: vault-0.10.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true

    log_level     = "Debug"

    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
      tls_key_file  = "/vault/userconfig/vault-server-tls/vault.key"
      tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
      tls_disable_client_certs = true

      telemetry {
        unauthenticated_metrics_access = "true"
      }

    }

    storage "raft" {
      path = "/vault/data"

      retry_join {
        leader_api_addr = "https://vault-0.slac.stanford.edu:8200/"
        leader_ca_cer_file = "/vault/userconfig/vault-server-tls/vault.ca"
        leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
      }      
      retry_join {
        leader_api_addr = "https://vault-1.slac.stanford.edu:8200/"
        leader_ca_cer_file = "/vault/userconfig/vault-server-tls/vault.ca"
        leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
      }
      retry_join {
        leader_api_addr = "https://vault-2.slac.stanford.edu:8200/"
        leader_ca_cer_file = "/vault/userconfig/vault-server-tls/vault.ca"
        leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
        leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
      }

    }

    service_registration "kubernetes" {}
---
