apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault--prod
spec:
  replicas: 3 
  template:
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
        #nodeAffinity:
        #  requiredDuringSchedulingIgnoredDuringExecution:
        #    nodeSelectorTerms:
        #    - matchExpressions:
        #      - key: type # Replace this with corresponding worker node label's key
        #        operator: In
        #        values:
        #        - general # Replace this with corresponding worker node label's value
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "vault" 
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
