apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  replicas: 1
  template:
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname
#                operator: In
#                values:
#                - sdfk8sext001
      containers:
      - name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        env:
        - name: HTTP_PROXY
          value: http://squid.slac.stanford.edu:3128
        - name: HTTPS_PROXY
          value: http://squid.slac.stanford.edu:3128
        - name: NO_PROXY
          value: kubernetes,10.96.0.1,localhost,.localdomain,squid.slac.stanford.edu,.slac.stanford.edu
#
