apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: auth-system
  labels:
    app: test
spec:
  serviceAccountName: dex
  containers:
    - name: test
      image: burtlo/devwebapp-ruby:k8s
      env:
        - name: VAULT_ADDR
          value: https://vault.slac.stanford.edu
        - name: VAULT_TOKEN
          value: root
