apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  #type: LoadBalancer
  #externalTrafficPolicy: Local
  ports:
  - name: api
    protocol: TCP
    port: 8086
  selector:
    app: influxdb

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-metallb
  labels:
    app: influxdb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    protocol: TCP
    port: 8086
  selector:
    app: influxdb


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "134.79.0.0/16,172.16.0.0/12"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
  - host: influxdb.slac.stanford.edu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: influxdb
            port:
              name: api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb-dev
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "134.79.0.0/16,172.16.0.0/12,192.168.0.0/16,127.0.0.1/8"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  rules:
  - host: influxdb-dev.slac.stanford.edu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: influxdb
            port:
              name: api
