kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-prod--data
  labels:
    type: local
spec:
  storageClassName: influxdb-prod--data
  capacity:
    storage: 100000Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
  #  path: /var/lib/influxdb
  local:
    path: /var/lib/influxdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - influxdb04
