apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vouch
  namespace: auth-system
  annotations:
spec:
  rules:
  - host: vouch.slac.stanford.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vouch
            port:
              name: http
