namespace: auth-system

bases:
- ../../base

secretGenerator:
- name: vouch-config
  files:
  - etc/config.yml
  - etc/.secrets/oidc-secret

patchesStrategicMerge:
- ingress-patch.yaml

images:
- name: quay.io/vouch/vouch-proxy
  newTag: '0.37'
