apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    role: postgres
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    name: pgbouncer
spec:
  ports:
  - port: 6432
    targetPort: 6432
  selector:
    role: pgbouncer
  type: LoadBalancer

